
* Libraries: they are collection of modules and functions to perform specific tasks.
* Pandas :  Data Manipulation
* series - 1D,dataframe- table -2D
* Numpy (numerical python): multi-dimensional arrays and mathematical operations
* matplotlib,seabor,plotly: data visualization
* statistics:(check the quality of data)

      *sklearn (scikit learn):machine learning -tabular numerical data
      *keras:deep learning
      *Tensorflow:google
      *pytorch:facebook

#### raw fact 
my name is deepak and i am from salem

#### data:
deepak
salem


#### format:
students data - tabular datas 
image,video
audio, resume
documentary

In [3]:
l1=[1,2,3,4,5]
l1

[1, 2, 3, 4, 5]

In [1]:
## !pip install pandas
import pandas as pd

In [4]:
pd.Series(l1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
student_details={"stu_id":[1,2,3,4,5],
                 "name":["deepak","gokul","arun","hari","kumar"],
                 "total_marks":[50,60,70,80,90],
                 "place":["mettur","salem","haveri","andhra","chennai"]}

In [6]:
student_details

{'stu_id': [1, 2, 3, 4, 5],
 'name': ['deepak', 'gokul', 'arun', 'hari', 'kumar'],
 'total_marks': [50, 60, 70, 80, 90],
 'place': ['mettur', 'salem', 'haveri', 'andhra', 'chennai']}

In [7]:
d1=pd.DataFrame(student_details)

In [8]:
d1

   stu_id    name  total_marks    place
0       1  deepak           50   mettur
1       2   gokul           60    salem
2       3    arun           70   haveri
3       4    hari           80   andhra
4       5   kumar           90  chennai

In [9]:
emp=pd.read_excel("D:\Excel datasets\Election result analysis\python datasets\emp_data.xlsx")
emp

   eid ename   sal  dept
0    1    aa  1234    10
1    2    bb  2345    20
2    3    cc  3214    30
3    4    dd  5332    40

In [17]:
mt=pd.read_csv("D:\Excel datasets\Election result analysis\python datasets\mtcars.csv")
mt

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [11]:
ctl=pd.read_table("D:\Excel datasets\Election result analysis\python datasets\chipotle.tsv")
ctl

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [12]:
stu=pd.read_csv("D:\Excel datasets\Election result analysis\python datasets\studata.txt")
stu

   sid    sname            emialid address  phoneno
0    1    priya    priya@gmail.com     dvg     9876
1    2  karthik  karthik@gmail.com     blr    12345
2    3    karan                NaN     msr    34567

In [18]:
###data intial anlysis
mt

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [19]:
mt.shape

(32, 12)

In [20]:
mt.shape[0]

32

In [21]:
mt.shape[1]

12

In [22]:
mt.columns

Index(['manufacturer', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs',
       'am', 'gear', 'carb'],
      dtype='object')

In [23]:
mt.dtypes

manufacturer     object
mpg             float64
cyl               int64
disp            float64
hp                int64
drat            float64
wt              float64
qsec            float64
vs                int64
am                int64
gear              int64
carb              int64
dtype: object

In [24]:
mt.isna().sum()

manufacturer    0
mpg             0
cyl             0
disp            0
hp              0
drat            0
wt              0
qsec            0
vs              0
am              0
gear            0
carb            0
dtype: int64

In [21]:
mt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   manufacturer  32 non-null     object
 1   mpg           32 non-null     float64
 2   cyl           32 non-null     int64
 3   disp          32 non-null     float64
 4   hp            32 non-null     int64
 5   drat          32 non-null     float64
 6   wt            32 non-null     float64
 7   qsec          32 non-null     float64
 8   vs            32 non-null     int64
 9   am            32 non-null     int64
 10  gear          32 non-null     int64
 11  carb          32 non-null     int64
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB

In [25]:
mt["cyl"].unique()

array([6, 4, 8])

In [26]:
mt["cyl"].nunique()

3

In [24]:
# print unique values from each column
for i in mt.columns:
    print(i,mt[i].nunique())
    print(mt[i].unique())

manufacturer 32
['Mazda RX4' 'Mazda RX4 Wag' 'Datsun 710' 'Hornet 4 Drive'
 'Hornet Sportabout' 'Valiant' 'Duster 360' 'Merc 240D' 'Merc 230'
 'Merc 280' 'Merc 280C' 'Merc 450SE' 'Merc 450SL' 'Merc 450SLC'
 'Cadillac Fleetwood' 'Lincoln Continental' 'Chrysler Imperial' 'Fiat 128'
 'Honda Civic' 'Toyota Corolla' 'Toyota Corona' 'Dodge Challenger'
 'AMC Javelin' 'Camaro Z28' 'Pontiac Firebird' 'Fiat X1-9' 'Porsche 914-2'
 'Lotus Europa' 'Ford Pantera L' 'Ferrari Dino' 'Maserati Bora'
 'Volvo 142E']
mpg 25
[21.  22.8 21.4 18.7 18.1 14.3 24.4 19.2 17.8 16.4 17.3 15.2 10.4 14.7
 32.4 30.4 33.9 21.5 15.5 13.3 27.3 26.  15.8 19.7 15. ]
cyl 3
[6 4 8]
disp 27
[160.  108.  258.  360.  225.  146.7 140.8 167.6 275.8 472.  460.  440.
  78.7  75.7  71.1 120.1 318.  304.  350.  400.   79.  120.3  95.1 351.
 145.  301.  121. ]
hp 22
[110  93 175 105 245  62  95 123 180 205 215 230  66  52  65  97 150  91
 113 264 335 109]
drat 22
[3.9  3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.07 2.93 3.   3.23 4.08 4.93
 4.22 3.7  3.73 4.43 3.77 3.62 3.54 4.11]
wt 29
[2.62  2.875 2.32  3.215 3.44  3.46  3.57  3.19  3.15  4.07  3.73  3.78
 5.25  5.424 5.345 2.2   1.615 1.835 2.465 3.52  3.435 3.84  3.845 1.935
 2.14  1.513 3.17  2.77  2.78 ]
qsec 30
[16.46 17.02 18.61 19.44 20.22 15.84 20.   22.9  18.3  18.9  17.4  17.6
 18.   17.98 17.82 17.42 19.47 18.52 19.9  20.01 16.87 17.3  15.41 17.05
 16.7  16.9  14.5  15.5  14.6  18.6 ]
vs 2
[0 1]
am 2
[1 0]
gear 3
[4 3 5]
carb 6
[4 1 2 3 6 8]

In [25]:
mt[ ["mpg"]]

     mpg
0   21.0
1   21.0
2   22.8
3   21.4
4   18.7
5   18.1
6   14.3
7   24.4
8   22.8
9   19.2
10  17.8
11  16.4
12  17.3
13  15.2
14  10.4
15  10.4
16  14.7
17  32.4
18  30.4
19  33.9
20  21.5
21  15.5
22  15.2
23  13.3
24  19.2
25  27.3
26  26.0
27  30.4
28  15.8
29  19.7
30  15.0
31  21.4

In [26]:
mt.cyl

0     6
1     6
2     4
3     6
4     8
5     6
6     8
7     4
8     4
9     6
10    6
11    8
12    8
13    8
14    8
15    8
16    8
17    4
18    4
19    4
20    4
21    8
22    8
23    8
24    8
25    4
26    4
27    4
28    8
29    6
30    8
31    4
Name: cyl, dtype: int64

In [27]:
mt[['mpg','cyl','gear','carb']]

     mpg  cyl  gear  carb
0   21.0    6     4     4
1   21.0    6     4     4
2   22.8    4     4     1
3   21.4    6     3     1
4   18.7    8     3     2
5   18.1    6     3     1
6   14.3    8     3     4
7   24.4    4     4     2
8   22.8    4     4     2
9   19.2    6     4     4
10  17.8    6     4     4
11  16.4    8     3     3
12  17.3    8     3     3
13  15.2    8     3     3
14  10.4    8     3     4
15  10.4    8     3     4
16  14.7    8     3     4
17  32.4    4     4     1
18  30.4    4     4     2
19  33.9    4     4     1
20  21.5    4     3     1
21  15.5    8     3     2
22  15.2    8     3     2
23  13.3    8     3     4
24  19.2    8     3     2
25  27.3    4     4     1
26  26.0    4     5     2
27  30.4    4     5     2
28  15.8    8     5     4
29  19.7    6     5     6
30  15.0    8     5     8
31  21.4    4     4     2

##### Slicing in pandas
* iloc(index location) - its based on row/col index value


* var.iloc[row index,col index]
* var.iloc[rst:rsp:rss,cst:csp:css]
* default start value:0
*        stop value: upto last
*        step size:1

* loc - its based on row/col name

In [28]:
# extract 1st rows with 1st 5 columns
mt.iloc[0:5,0:5]

        manufacturer   mpg  cyl   disp   hp
0          Mazda RX4  21.0    6  160.0  110
1      Mazda RX4 Wag  21.0    6  160.0  110
2         Datsun 710  22.8    4  108.0   93
3     Hornet 4 Drive  21.4    6  258.0  110
4  Hornet Sportabout  18.7    8  360.0  175

In [29]:
# extract entire table with iloc
mt.iloc[:,:]

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [30]:
# rows with last 5 columns
mt.iloc[:,-5:]

     qsec  vs  am  gear  carb
0   16.46   0   1     4     4
1   17.02   0   1     4     4
2   18.61   1   1     4     1
3   19.44   1   0     3     1
4   17.02   0   0     3     2
5   20.22   1   0     3     1
6   15.84   0   0     3     4
7   20.00   1   0     4     2
8   22.90   1   0     4     2
9   18.30   1   0     4     4
10  18.90   1   0     4     4
11  17.40   0   0     3     3
12  17.60   0   0     3     3
13  18.00   0   0     3     3
14  17.98   0   0     3     4
15  17.82   0   0     3     4
16  17.42   0   0     3     4
17  19.47   1   1     4     1
18  18.52   1   1     4     2
19  19.90   1   1     4     1
20  20.01   1   0     3     1
21  16.87   0   0     3     2
22  17.30   0   0     3     2
23  15.41   0   0     3     4
24  17.05   0   0     3     2
25  18.90   1   1     4     1
26  16.70   0   1     5     2
27  16.90   1   1     5     2
28  14.50   0   1     5     4
29  15.50   0   1     5     6
30  14.60   0   1     5     8
31  18.60   1   1     4     2

In [31]:
# extract all the col with divisible of 3 row index
mt.iloc[3::3,:]

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8

In [32]:
# even index col and odd index rows
mt.iloc[1::2,2::2]

    cyl   hp     wt  vs  gear
1     6  110  2.875   0     4
3     6  110  3.215   1     3
5     6  105  3.460   1     3
7     4   62  3.190   1     4
9     6  123  3.440   1     4
11    8  180  4.070   0     3
13    8  180  3.780   0     3
15    8  215  5.424   0     3
17    4   66  2.200   1     4
19    4   65  1.835   1     4
21    8  150  3.520   0     3
23    8  245  3.840   0     3
25    4   66  1.935   1     4
27    4  113  1.513   1     5
29    6  175  2.770   0     5
31    4  109  2.780   1     4

2,5,8,13,19 rows
3,6,11 col

In [33]:
temp=mt.iloc[[2,5,8,13,19],[3,6,11]]
temp

     disp     wt  carb
2   108.0  2.320     1
5   225.0  3.460     1
8   140.8  3.150     2
13  275.8  3.780     3
19   71.1  1.835     1

loc:
manufacurer , cyl,hp=cols
2,5,9,12 = rows

In [34]:
mt.loc[[2,5,9,12],["manufacturer","cyl","hp"]]

   manufacturer  cyl   hp
2    Datsun 710    4   93
5       Valiant    6  105
9      Merc 280    6  123
12   Merc 450SL    8  180

In [28]:
mt.loc[0:4,"manufacturer":"hp"]

        manufacturer   mpg  cyl   disp   hp
0          Mazda RX4  21.0    6  160.0  110
1      Mazda RX4 Wag  21.0    6  160.0  110
2         Datsun 710  22.8    4  108.0   93
3     Hornet 4 Drive  21.4    6  258.0  110
4  Hornet Sportabout  18.7    8  360.0  175

In [36]:
# add,update,delete on table
temp = mt
temp

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [37]:
temp['half carb']=temp['carb']/2
temp

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,half carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,2.0
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,2.0
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,0.5
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,0.5
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,1.0
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,0.5
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,2.0
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,1.0
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,1.0
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,2.0
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,2.0
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,1.5
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,1.5
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,1.5
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,2.0
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,2.0
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,2.0
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,0.5
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,1.0
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,0.5
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,0.5
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,1.0
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,1.0
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,2.0
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,1.0
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,0.5
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,1.0
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,1.0
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,2.0
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,3.0
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,4.0
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,1.0

In [38]:
temp['gear']=temp['gear']+10
temp

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,half carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,14,4,2.0
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,14,4,2.0
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,14,1,0.5
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,13,1,0.5
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,13,2,1.0
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,13,1,0.5
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,13,4,2.0
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,14,2,1.0
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,14,2,1.0
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,14,4,2.0
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,14,4,2.0
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,13,3,1.5
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,13,3,1.5
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,13,3,1.5
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,13,4,2.0
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,13,4,2.0
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,13,4,2.0
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,14,1,0.5
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,14,2,1.0
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,14,1,0.5
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,13,1,0.5
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,13,2,1.0
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,13,2,1.0
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,13,4,2.0
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,13,2,1.0
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,14,1,0.5
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,15,2,1.0
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,15,2,1.0
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,15,4,2.0
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,15,6,3.0
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,15,8,4.0
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,14,2,1.0

In [39]:
del temp['half carb']

In [40]:
temp

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,14,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,14,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,14,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,13,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,13,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,13,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,13,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,14,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,14,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,14,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,14,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,13,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,13,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,13,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,13,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,13,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,13,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,14,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,14,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,14,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,13,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,13,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,13,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,13,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,13,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,14,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,15,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,15,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,15,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,15,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,15,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,14,2

In [41]:
temp.drop(columns=['wt','qsec','vs','am'],inplace=True)

In [42]:
temp

           manufacturer   mpg  cyl   disp   hp  drat  gear  carb
0             Mazda RX4  21.0    6  160.0  110  3.90    14     4
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90    14     4
2            Datsun 710  22.8    4  108.0   93  3.85    14     1
3        Hornet 4 Drive  21.4    6  258.0  110  3.08    13     1
4     Hornet Sportabout  18.7    8  360.0  175  3.15    13     2
5               Valiant  18.1    6  225.0  105  2.76    13     1
6            Duster 360  14.3    8  360.0  245  3.21    13     4
7             Merc 240D  24.4    4  146.7   62  3.69    14     2
8              Merc 230  22.8    4  140.8   95  3.92    14     2
9              Merc 280  19.2    6  167.6  123  3.92    14     4
10            Merc 280C  17.8    6  167.6  123  3.92    14     4
11           Merc 450SE  16.4    8  275.8  180  3.07    13     3
12           Merc 450SL  17.3    8  275.8  180  3.07    13     3
13          Merc 450SLC  15.2    8  275.8  180  3.07    13     3
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93    13     4
15  Lincoln Continental  10.4    8  460.0  215  3.00    13     4
16    Chrysler Imperial  14.7    8  440.0  230  3.23    13     4
17             Fiat 128  32.4    4   78.7   66  4.08    14     1
18          Honda Civic  30.4    4   75.7   52  4.93    14     2
19       Toyota Corolla  33.9    4   71.1   65  4.22    14     1
20        Toyota Corona  21.5    4  120.1   97  3.70    13     1
21     Dodge Challenger  15.5    8  318.0  150  2.76    13     2
22          AMC Javelin  15.2    8  304.0  150  3.15    13     2
23           Camaro Z28  13.3    8  350.0  245  3.73    13     4
24     Pontiac Firebird  19.2    8  400.0  175  3.08    13     2
25            Fiat X1-9  27.3    4   79.0   66  4.08    14     1
26        Porsche 914-2  26.0    4  120.3   91  4.43    15     2
27         Lotus Europa  30.4    4   95.1  113  3.77    15     2
28       Ford Pantera L  15.8    8  351.0  264  4.22    15     4
29         Ferrari Dino  19.7    6  145.0  175  3.62    15     6
30        Maserati Bora  15.0    8  301.0  335  3.54    15     8
31           Volvo 142E  21.4    4  121.0  109  4.11    14     2

In [46]:
# extract data of 8 cyl cars
mt[mt['cyl']==8]

           manufacturer   mpg  cyl   disp   hp  drat  gear  carb
4     Hornet Sportabout  18.7    8  360.0  175  3.15    13     2
6            Duster 360  14.3    8  360.0  245  3.21    13     4
11           Merc 450SE  16.4    8  275.8  180  3.07    13     3
12           Merc 450SL  17.3    8  275.8  180  3.07    13     3
13          Merc 450SLC  15.2    8  275.8  180  3.07    13     3
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93    13     4
15  Lincoln Continental  10.4    8  460.0  215  3.00    13     4
16    Chrysler Imperial  14.7    8  440.0  230  3.23    13     4
21     Dodge Challenger  15.5    8  318.0  150  2.76    13     2
22          AMC Javelin  15.2    8  304.0  150  3.15    13     2
23           Camaro Z28  13.3    8  350.0  245  3.73    13     4
24     Pontiac Firebird  19.2    8  400.0  175  3.08    13     2
28       Ford Pantera L  15.8    8  351.0  264  4.22    15     4
30        Maserati Bora  15.0    8  301.0  335  3.54    15     8

In [50]:
# extract data automatic car with hp greater than 100
mt[(mt['am']==1) & (mt['hp']>100)]

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [3]:
mt

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [ ]:
# extract records who's millage range is 10 to 20   
mt[(mt['mpg']>=10) & (mt['mpg']<=20)]

In [54]:
# extract data of either 6 cyl or 4 gear
mt[(mt['cyl']==6) | (mt['gear']==4)]

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [59]:
# calculate mpg max,min,avg
mt['mpg'].max()

33.9

In [60]:
mt['mpg'].min()

10.4

In [63]:
print(mt['mpg'].mean())

20.090625000000003

In [34]:
mt['mpg'].agg(['max','min','mean'])

max     33.900000
min     10.400000
mean    20.090625
Name: mpg, dtype: float64

In [66]:
mt.describe(include='all')

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
unique,32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Mazda RX4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,NaN,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,NaN,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,NaN,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,NaN,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,NaN,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,NaN,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [4]:
mt.set_index('manufacturer')

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
manufacturer,,,,,,,,,,,
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [2]:
import pandas as pd

In [3]:
sale1=pd.read_csv("Sales Transactions-2017.csv")
sale2=pd.read_csv("Sales Transactions-2018.csv")
sale3=pd.read_csv("Sales Transactions-2019.csv")

In [5]:
sale1

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
47285,31/03/2018,Sal:10042,Vkp,10*10 SHEET,25,137,"3,425.00",NaN,"3,425.00"
47286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47288,NaN,Total,NaN,NaN,"607,734.60","669,300.49","9,953,816.13","106,607.00","9,868,583.13"
47289,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71"

In [4]:
sale2

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2018,Sal:146,TP13,SILVER POUCH 9*12,50,85,"4,250.00",NaN,"66,724.00"
1,1/4/2018,Sal:146,TP13,RUBBER,5,290,"1,450.00",NaN,NaN
2,1/4/2018,Sal:146,TP13,DURGA 10*12 Blue,"1,600.00",5.5,"8,800.00",NaN,NaN
3,1/4/2018,Sal:146,TP13,DURGA 13*16 BLUE,400,11,"4,400.00",NaN,NaN
4,1/4/2018,Sal:146,TP13,10*12 SARAS-NAT,600,8.1,"4,860.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
44735,31/03/2019,Sal:9610,HAMPI FOODS,SPOON SOOFY,200,40,"8,000.00",NaN,NaN
44736,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44737,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44738,NaN,Total,NaN,NaN,"666,056.00","1,067,808.80","10,796,991.30","29,999.00","10,787,647.30"
44739,NaN,Total,NaN,NaN,"7,097,803.00","10,024,197.00","117,897,671.80","720,204.00","117,427,983.80"

In [5]:
sale3

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2019,Sal:687,BALAJI PLASTICS,DONA-VAI-9100,1,"1,730.00","1,730.00",NaN,"3,460.00"
1,1/4/2019,Sal:687,BALAJI PLASTICS,SMART BOUL(48),1,"1,730.00","1,730.00",NaN,NaN
2,1/4/2019,Sal:688,BALAJI PLASTICS,Vishnu Ice,110,18.5,"2,035.00",NaN,"2,035.00"
3,,,28/3,,0,0,,,
4,1/4/2019,Sal:689,BALAJI PLASTICS,100LEAF -SP,3,585,"1,755.00",NaN,"1,755.00"
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [6]:
sales = pd.concat([sale1,sale2,sale3],ignore_index=True)
sales

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
111201,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
111202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111204,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
111205,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [ ]:
on mt cars 
1) how to rename the column 
2) and how to make manufacturer as row index name 

on insurace data
1)each region wise total expenses 
2)each region, each children and smoker class wise total expenses 
3) gender wise avg bmi and

In [12]:
sales.rename(columns={'Disc':'Price','Voucher Amount':'VA'})

,Date,Voucher,Party,Product,Qty,Rate,Gross,Price,VA
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2.0,NaN,NaN,NaN,NaN
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6.0,NaN,NaN,NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23.0,NaN,NaN,NaN
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6.0,NaN,NaN,NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
111201,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400.0,16.0,NaN,NaN,NaN
111202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111204,NaN,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111205,NaN,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
sales.set_index('Date')

,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
Date,,,,,,,,
1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2.0,NaN,NaN,NaN,NaN
1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6.0,NaN,NaN,NaN,NaN
1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23.0,NaN,NaN,NaN
1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6.0,NaN,NaN,NaN,NaN
1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400.0,16.0,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
sales.columns

Index(['Date', 'Voucher', 'Party', 'Product', 'Qty', 'Rate', 'Gross', 'Disc',
       'Voucher Amount'],
      dtype='object')

In [15]:
sales.dtypes

Date               object
Voucher            object
Party              object
Product            object
Qty               float64
Rate              float64
Gross             float64
Disc              float64
Voucher Amount    float64
dtype: object

In [8]:
sales['Qty']=pd.to_numeric(sales['Qty'],errors='coerce')
sales['Rate']=pd.to_numeric(sales['Rate'],errors='coerce')
sales['Gross']=pd.to_numeric(sales['Gross'],errors='coerce')
sales['Disc']=pd.to_numeric(sales['Disc'],errors='coerce')
sales['Voucher Amount']=pd.to_numeric(sales['Voucher Amount'],errors='coerce')

In [16]:
sales.dtypes

Date               object
Voucher            object
Party              object
Product            object
Qty               float64
Rate              float64
Gross             float64
Disc              float64
Voucher Amount    float64
dtype: object